### ISSUE TITLE
Hover over the menu

### ISSUE THREAD

**Issue by shadeed** [shadeed/iShadeed-Blog#1]
When hovering over a menu item, the others will move.

**Comment by shadeed** [comment]
the problem is that the a tag doesn't have padding

// Before //
.menu ul li a
{
    text-decoration: none;
    color: #343434;
}

.menu ul li a:hover
{
    background-color: #ededed;
    padding: 6px 19px 8px 19px;
}

// After //
.menu ul li a
{
    text-decoration: none;
    color: #343434;
padding: 6px 19px 8px 19px;
}

.menu ul li a:hover
{
    background-color: #ededed;
    padding: 6px 19px 8px 19px;
}

**Comment by shadeed** [comment]
![screen shot 2014-07-03 at 6 18 55 pm](https://cloud.githubusercontent.com/assets/8038659/3471707/29490364-02c5-11e4-837a-2ad5d595e69c.png)
The problem now is the too much space between the items

**Comment by aymanfarhat** [comment]
Quick tip. Don't use padding to seperate elements,use margin instead. Margin is for seperation of an element against its outer surrounding. Padding is inside for itself.

Make sure you understand the CSS Box model, here is a very good post: http://css-tricks.com/the-css-box-model/

In addition any code update even if its not final make sure you add it in the repo as a commit so other collaborators can pull and try locally directly.
