### ISSUE TITLE
Thumbnail hover

### ISSUE THREAD

**Issue by shadeed** [shadeed/iShadeed-Blog#3]
When hovering over a project thumbnail, the title "Instagram Redesign" should be blue. I didn't know how to change it color when hovering over the thumbnail.

**Comment by aymanfarhat** [comment]
You can use the hover selector over the containing div and continue your selector with the rest of the children inside the parent that you want to apply the property over. In this case, the title is an h1 inside a div with class meta, inside the original parent(div with class project1) Example:

`.project1:hover .meta h1 {
     color: red;
}`

**Comment by shadeed** [comment]
Thanks :+1:  That works!

**Comment by aymanfarhat** [comment]
Great make sure to close an issue was solved. You can also reference an issue from your commits. Example commit message: "Fixed #3" 

http://stackoverflow.com/questions/1687262/link-to-github-issue-number-with-commit-message
